using System.Collections.Immutable;
using System.Text;

namespace Jcc.Commons.Platform.Generators;

/// <summary>
/// Generador de código responsable de crear las extensiones de inyección de dependencias
/// para los manejadores de consultas detectados.
/// </summary>
internal static class QueryHandlerCodeGenerator
{
    /// <summary>
    /// Genera el código completo para registrar todos los QueryHandlers en el contenedor DI.
    /// </summary>
    public static string GenerateDependencyInjectionCode(ImmutableArray<QueryHandlerInfo> handlers)
    {
        var sb = new StringBuilder();
        
        // Encabezado y usando
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Este archivo fue generado automáticamente por QueryHandlerSourceGenerator");
        sb.AppendLine();
        sb.AppendLine("using Jcc.Commons.Platform.Domain;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // Agrupar handlers por namespace
        var handlersByNamespace = handlers
            .GroupBy(h => h.Namespace)
            .OrderBy(g => g.Key);

        // Generar registros de dependencias
        sb.AppendLine("namespace Jcc.Commons.Platform.Infraestructure.Configuration;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extensiones de inyección de dependencias auto-generadas para QueryHandlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class DependencyInjectionConfig");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registra automáticamente todos los QueryHandlers en el contenedor de servicios.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddGeneratedQueryHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (services == null) throw new ArgumentNullException(nameof(services));");
        sb.AppendLine();

        // Registrar cada handler
        foreach (var handler in handlers.OrderBy(h => h.ClassName))
        {
            sb.AppendLine($"        // Registrar {handler.ClassName}");
            sb.AppendLine($"        services.AddScoped(typeof({handler.InterfaceFullName}), typeof({handler.FullClassName}));");
            sb.AppendLine($"        services.AddScoped(typeof({handler.FullClassName}));");
            sb.AppendLine();
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}